kind: DeploymentConfig
apiVersion: apps.openshift.io/v1
metadata:
  name: {{oc_app_name}}
  namespace: {{oc_project}}
spec:
  triggers:
    - type: {{oc_app_name}}
      imageChangeParams:
        automatic: true
        containerNames:
          {{oc_app_name}}
        from:
          kind: ImageStreamTag
          namespace: {{oc_project}}
          name: '{{oc_app_name}}:latest'
    - type: ConfigChange
  replicas: 1
  selector:
    deploymentConfig: {{oc_app_name}}
    name: {{oc_app_name}}
  template:
    metadata:
      labels:
        deploymentConfig: {{oc_app_name}}
        name: {{oc_app_name}}
    spec:
      containers:
        - name: {{oc_app_name}}
          image: {{oc_app_repo}}/{{oc_project}}/{{oc_app_name}}:{{oc_app_version}}
          resources: {}
