kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{oc_app_name}}
  namespace: {{oc_project}}
spec:
  host: {{oc_host_name}}
  to:
    kind: Service
    name: {{oc_app_name}}
  port:
    targetPort: 8080-tcp
  tls:
    termination: edge
  wildcardPolicy: None