-- liquibase formatted sql

-- changeset Carlo_Castro:1663647419952-1
CREATE TABLE company (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, address1 VARCHAR(50) NULL, address2 VARCHAR(50) NULL, city VARCHAR(30) NULL, year datetime NULL, CONSTRAINT PK_COMPANY PRIMARY KEY (id));

-- changeset Carlo_Castro:1663647419952-2
CREATE TABLE person (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(50) NOT NULL, address1 VARCHAR(50) NULL, address2 VARCHAR(50) NULL, city VARCHAR(30) NULL, CONSTRAINT PK_PERSON PRIMARY KEY (id));

-- changeset Carlo_Castro:1663647419952-3
CREATE TABLE user (id BIGINT AUTO_INCREMENT NOT NULL, timestamp datetime NULL, inactive CHAR(1) NOT NULL, username VARCHAR(50) NOT NULL, address1 VARCHAR(50) NULL, address2 VARCHAR(50) NULL, city VARCHAR(30) NULL, CONSTRAINT PK_USER PRIMARY KEY (id));

