CREATE TABLE IF NOT EXISTS public.customer
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone,
    modified_at timestamp without time zone,
    birth_date timestamp without time zone,
    first_name character varying(50),
    last_name character varying(50),
    address character varying(50),
    customer_auth_id bigint,
    CONSTRAINT customer_pkey PRIMARY KEY (id)
)
