
CREATE TABLE IF NOT EXISTS public.personal_information
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone,
    modified_at timestamp without time zone,
    age integer,
    birth_date timestamp without time zone,
    first_name character varying(50) COLLATE pg_catalog."default",
    last_name character varying(50) COLLATE pg_catalog."default",
    middle_name character varying(50) COLLATE pg_catalog."default",
    employee_num character varying(10) COLLATE pg_catalog."default",
    CONSTRAINT personal_information_pkey PRIMARY KEY (id)
)
