
CREATE TABLE IF NOT EXISTS public.login_credentials
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp without time zone,
    modified_at timestamp without time zone,
    password character varying(50) COLLATE pg_catalog."default",
    user_id integer,
    username character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT login_credentials_pkey PRIMARY KEY (id)
)
